configuration: |-
  [mysqld]
  default_authentication_plugin=mysql_native_password
  skip-name-resolve
  explicit_defaults_for_timestamp
  basedir=/opt/bitnami/mysql
  plugin_dir=/opt/bitnami/mysql/lib/plugin
  port=3306
  socket=/opt/bitnami/mysql/tmp/mysql.sock
  datadir=/bitnami/mysql/data
  tmpdir=/opt/bitnami/mysql/tmp
  max_allowed_packet=16M
  bind-address=*
  pid-file=/opt/bitnami/mysql/tmp/mysqld.pid
  log-error=/opt/bitnami/mysql/logs/mysqld.log
  character-set-server=UTF8
  collation-server=utf8_general_ci
  slow_query_log=0
  slow_query_log_file=/opt/bitnami/mysql/logs/mysqld.log
  long_query_time=10.0
  server-id=223344
  log_bin=mysql-bin
  binlog_format=row
  binlog_row_image=full
  expire_logs_days=0